apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-action
  template:
    metadata:
      labels:
        app: github-action
    spec:
      containers:
        - name: app
          image: us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE:$TAG
          ports:
         - containerPort: 80
