apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-action
  template:
    metadata:
      labels:
        app: github-action
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
