name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: sudhakar-test-ak
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: github-action
  IMAGE: test
  TAG: 1.0.1
  REPO_NAME : sudhakar-test

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud auth configure-docker  us-central1-docker.pkg.dev
      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials sudhakar-ak-test --zone us-central1-c
      - name: Build Docker Image
        run: |-
          docker build --tag "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE:$TAG" .
      - name: Publish Docker Image to GCR
        run: |-
          docker push "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE:$TAG"
      - name: Set up Kustomize file
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
